name: Notify on Complete

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commit messages for keywords
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const keywords = ['task complete', 'build finished']
            const payload = context.payload
            const commits = payload.commits || []
            let match = false
            for (const c of commits) {
              const msg = (c.message || '').toLowerCase()
              if (keywords.some(k => msg.includes(k))) {
                match = true
                break
              }
            }
            if (!match && payload.head_commit) {
              const msg = (payload.head_commit.message || '').toLowerCase()
              if (keywords.some(k => msg.includes(k))) {
                match = true
              }
            }
            core.setOutput('should_notify', match ? 'true' : 'false')

  # Email step removed: YAHOO_SMTP_* secrets not in use
      - name: Notification
        if: steps.check.outputs.should_notify == 'true'
        run: echo "✅ Deployment complete."
